channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pandas
  - spacy

  # from requirements.txt
  - python-dateutil>=2.6.1
  - gensim>=3.4.0
  - pytest>=5.3.2
  - tqdm>=4.26.0
  - segtok>=1.5.7
  - matplotlib>=2.2.3
  - mpld3==0.3
  - scikit-learn>=0.21.3
  - sqlitedict>=1.6.0
  - deprecated>=1.2.4
  - hyperopt>=0.1.1
  - regex
  - tabulate
  - langdetect
  - pip
  - pip:
    - bpemb>=0.2.9
    - transformers>=2.6.0


